-- Tabla de proveedores
CREATE TABLE proveedor (
    id_proveedor INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR(100) NOT NULL,
    telefono VARCHAR(15)
);

-- Tabla de clientes
CREATE TABLE cliente (
    id_cliente INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR(100) NOT NULL,
    telefono VARCHAR(15)
);

-- Tabla de direcciones (Dependiente de cliente)
CREATE TABLE direccion (
    id_direccion INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    calle VARCHAR(255) NOT NULL,
    ciudad VARCHAR(100) NOT NULL,
    codigo_postal VARCHAR(10) NOT NULL,
    id_cliente INT NOT NULL,
    CONSTRAINT fk_direccion_cliente FOREIGN KEY (id_cliente)
        REFERENCES cliente(id_cliente)
        ON DELETE CASCADE
);

-- Tabla de ventas (Dependiente de cliente)
CREATE TABLE venta (
    id_venta INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    fecha DATE NOT NULL,
    monto_total NUMERIC(10, 2) NOT NULL,
    id_cliente INT NOT NULL,
    CONSTRAINT fk_venta_cliente FOREIGN KEY (id_cliente)
        REFERENCES cliente(id_cliente)
        ON DELETE RESTRICT
);

-- Tabla supertipo de productos
CREATE TABLE producto (
    id_producto INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR(100) NOT NULL,
    descripcion TEXT,
    precio NUMERIC(10, 2) NOT NULL,
    cantidad_stock INT NOT NULL DEFAULT 0,
    id_proveedor INT NOT NULL,
    CONSTRAINT fk_producto_proveedor FOREIGN KEY (id_proveedor)
        REFERENCES proveedor(id_proveedor)
        ON DELETE RESTRICT
);

-- Tabla subtipo ropa
CREATE TABLE ropa (
    id_producto INT PRIMARY KEY,
    material VARCHAR(50) NOT NULL,
    tipo_corte VARCHAR(50),
    talla VARCHAR(10) NOT NULL,
    CONSTRAINT fk_ropa_producto FOREIGN KEY (id_producto)
        REFERENCES producto(id_producto)
        ON DELETE CASCADE
);

-- Tabla subtipo calzado
CREATE TABLE calzado (
    id_producto INT PRIMARY KEY,
    talla_numerica NUMERIC(3, 1) NOT NULL,
    material_suela VARCHAR(50) NOT NULL,
    CONSTRAINT fk_calzado_producto FOREIGN KEY (id_producto)
        REFERENCES producto(id_producto)
        ON DELETE CASCADE
);

-- Tabla subtipo accesorios
CREATE TABLE accesorios (
    id_producto INT PRIMARY KEY,
    material VARCHAR(50) NOT NULL,
    dimensiones VARCHAR(50),
    CONSTRAINT fk_accesorios_producto FOREIGN KEY (id_producto)
        REFERENCES producto(id_producto)
        ON DELETE CASCADE
);

-- Tabla asociativa para detalle de venta
CREATE TABLE detalle_venta (
    id_venta INT NOT NULL,
    id_producto INT NOT NULL,
    cantidad INT NOT NULL,
    precio_unitario NUMERIC(10, 2) NOT NULL,
    CONSTRAINT pk_detalle_venta PRIMARY KEY (id_venta, id_producto),
    CONSTRAINT fk_detalle_venta_venta FOREIGN KEY (id_venta)
        REFERENCES venta(id_venta)
        ON DELETE CASCADE,
    CONSTRAINT fk_detalle_venta_producto FOREIGN KEY (id_producto)
        REFERENCES producto(id_producto)
        ON DELETE RESTRICT
);